
export { Icon } from './src/components/icons/icon'

export * from './src/components/icons/components/add'
export * from './src/components/icons/components/arrow-down'
export * from './src/components/icons/components/arrow-left'
export * from './src/components/icons/components/arrow-left'
export * from './src/components/icons/components/arrow-right'
export * from './src/components/icons/components/arrow-up'
export * from './src/components/icons/components/chat'
export * from './src/components/icons/components/code'
export * from './src/components/icons/components/copy'
export * from './src/components/icons/components/home'
export * from './src/components/icons/components/left'
export * from './src/components/icons/components/minus'
export * from './src/components/icons/components/remove'
export * from './src/components/icons/components/right'
export * from './src/components/icons/components/user'
